repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-ast
    -   id: debug-statements
    -   id: requirements-txt-fixer

-   repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]
        args: [--max-line-length=79, --extend-ignore=E203, --extend-ignore=E266, --extend-ignore=E501]

-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
        language_version: python3
        args: [--line-length=79]
